// Code generated by protoc-gen-go.
// source: device.proto
// DO NOT EDIT!

/*
Package device is a generated protocol buffer package.

It is generated from these files:
	device.proto

It has these top-level messages:
	Device
*/
package device

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Device struct {
	Cid              *uint32 `protobuf:"varint,1,req,name=cid" json:"cid,omitempty"`
	Uid              *uint32 `protobuf:"varint,2,req,name=uid" json:"uid,omitempty"`
	Cmdid            *uint32 `protobuf:"varint,3,req,name=cmdid" json:"cmdid,omitempty"`
	Msg              *string `protobuf:"bytes,4,req,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}

func (m *Device) GetCid() uint32 {
	if m != nil && m.Cid != nil {
		return *m.Cid
	}
	return 0
}

func (m *Device) GetUid() uint32 {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return 0
}

func (m *Device) GetCmdid() uint32 {
	if m != nil && m.Cmdid != nil {
		return *m.Cmdid
	}
	return 0
}

func (m *Device) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func init() {
}
