// Code generated by protoc-gen-go.
// source: device.proto
// DO NOT EDIT!

/*
Package wspushd is a generated protocol buffer package.

It is generated from these files:
	device.proto

It has these top-level messages:
	Device
	Data
*/
package wspushd

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Device struct {
	Cmdid            *uint32 `protobuf:"varint,1,req,name=cmdid" json:"cmdid,omitempty"`
	Uid              *string `protobuf:"bytes,2,req,name=uid" json:"uid,omitempty"`
	Msg              *Data   `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}

func (m *Device) GetCmdid() uint32 {
	if m != nil && m.Cmdid != nil {
		return *m.Cmdid
	}
	return 0
}

func (m *Device) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *Device) GetMsg() *Data {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Data struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Data             []byte  `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}

func (m *Data) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Data) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
}
