/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: device.proto */

#ifndef PROTOBUF_C_device_2eproto__INCLUDED
#define PROTOBUF_C_device_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Device Device;


/* --- enums --- */


/* --- messages --- */

struct  _Device
{
  ProtobufCMessage base;
  uint32_t cid;
  uint32_t uid;
  uint32_t cmdid;
  char *msg;
};
#define DEVICE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&device__descriptor) \
    , 0, 0, 0, NULL }


/* Device methods */
void   device__init
                     (Device         *message);
size_t device__get_packed_size
                     (const Device   *message);
size_t device__pack
                     (const Device   *message,
                      uint8_t             *out);
size_t device__pack_to_buffer
                     (const Device   *message,
                      ProtobufCBuffer     *buffer);
Device *
       device__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   device__free_unpacked
                     (Device *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Device_Closure)
                 (const Device *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor device__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_device_2eproto__INCLUDED */
